# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07e78ae3b34c87ea3bd76b53a46a9d25ab646add895e862ecd2ed2a02d422b51e4ef94dbec04ec3dfcd2d0f30e82a79567d7f026cf7c3567e8e05c4bde04aced

test:
  secret_key_base: 6fe18bef5d5f3958055df17fff1aa8085ccf44f4b509b6a73d394b4896785f8662282fca181ba86d9c93af26bf9c63c3a6bbd024144277620e6174a71ce61198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
